# -*- coding: utf-8 -*-
"""permutation_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjSp-1rEh3DsSSf5YQ_YMgeV9ygzreuM
"""

"""
Permutation test for cross-linguistic SAE feature overlap.
Tests whether the universal slang core (features shared across
English, Hebrew, and Russian) is statistically non-accidental.

"""

import json
import argparse
import numpy as np




# ── Load feature sets ─────────────────────────────────────────────────────────

def load_feature_sets(json_path, top_k):
    with open(json_path) as f:
        data = json.load(f)

    pf = data["per_language_top_features"]
    sets = {}
    for lang in ("English", "Hebrew", "Russian"):
        ids = pf[lang]["top_100_feature_ids"][:top_k]
        sets[lang] = set(ids)
        print(f"  {lang}: {len(ids)} features loaded (using top {top_k})")
    return sets


# ── Observed overlaps ─────────────────────────────────────────────────────────

def compute_overlaps(sets):
    eng, heb, rus = sets["English"], sets["Hebrew"], sets["Russian"]
    triple   = eng & heb & rus
    en_he    = (eng & heb) - triple
    en_ru    = (eng & rus) - triple
    he_ru    = (heb & rus) - triple
    return {
        "triple":      len(triple),
        "en_he_excl":  len(en_he),
        "en_ru_excl":  len(en_ru),
        "he_ru_excl":  len(he_ru),
    }


# ── Permutation test ──────────────────────────────────────────────────────────

def run_permutation_test(observed, n_perm, top_k, n_feat, seed):
    rng = np.random.default_rng(seed)
    null = {k: np.zeros(n_perm, dtype=int) for k in observed}

    print(f"\nRunning {n_perm:,} permutations ...")
    for i in range(n_perm):
        r_eng = set(rng.choice(n_feat, top_k, replace=False))
        r_heb = set(rng.choice(n_feat, top_k, replace=False))
        r_rus = set(rng.choice(n_feat, top_k, replace=False))

        t = len(r_eng & r_heb & r_rus)
        null["triple"][i]     = t
        null["en_he_excl"][i] = len(r_eng & r_heb) - t
        null["en_ru_excl"][i] = len(r_eng & r_rus) - t
        null["he_ru_excl"][i] = len(r_heb & r_rus) - t

        if (i + 1) % 10_000 == 0:
            print(f"  {i+1:>7,} / {n_perm:,}")

    return null


# ── Results ───────────────────────────────────────────────────────────────────

LABELS = {
    "triple":     "Triple  (EN ∩ HE ∩ RU)",
    "en_he_excl": "EN ∩ HE (excl. triple) ",
    "en_ru_excl": "EN ∩ RU (excl. triple) ",
    "he_ru_excl": "HE ∩ RU (excl. triple) ",
}

def print_results(observed, null, top_k, n_feat, n_perm):
    print("\n" + "=" * 65)
    print(f"PERMUTATION TEST RESULTS  (n={n_perm:,} permutations)")
    print(f"Feature space: {n_feat:,}   Top-k: {top_k}")
    print("=" * 65)
    hdr = f"{'Overlap':<28} {'Obs':>4} {'E[null]':>8} {'Max(null)':>9} {'Fold':>8} {'p-value':>10}"
    print(hdr)
    print("-" * 65)

    for key, label in LABELS.items():
        obs  = observed[key]
        dist = null[key]
        mn   = dist.mean()
        mx   = dist.max()
        pval = (dist >= obs).mean()
        fold = obs / mn if mn > 0 else float("inf")

        pval_str = f"<{1/len(dist):.0e}" if pval == 0 else f"{pval:.2e}"
        fold_str = f"{fold:.0f}×" if fold != float("inf") else "∞"

        print(f"{label:<28} {obs:>4} {mn:>8.4f} {mx:>9} {fold_str:>8} {pval_str:>10}")

    print("=" * 65)

    # Analytical sanity check
    exp_triple = top_k**3 / n_feat**2
    exp_pair   = top_k**2 / n_feat
    print(f"\nAnalytical E[triple] under i.i.d. chance = {top_k}³ / {n_feat}² = {exp_triple:.5f}")
    print(f"Analytical E[pair]   under i.i.d. chance = {top_k}² / {n_feat}  = {exp_pair:.4f}")


# ── Optional plot ─────────────────────────────────────────────────────────────

def plot_null_distributions(observed, null):
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker

    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    fig.suptitle("Null distributions vs. observed overlap counts\n"
                 "(one-sided permutation test, n=100,000)", fontsize=13)

    colors = {"triple": "#d4a000", "en_he_excl": "#0099aa",
              "en_ru_excl": "#cc3380", "he_ru_excl": "#6633cc"}

    for ax, (key, label) in zip(axes.flat, LABELS.items()):
        dist = null[key]
        obs  = observed[key]
        vals, cnts = np.unique(dist, return_counts=True)
        pct = cnts / cnts.sum() * 100
        c   = colors[key]

        ax.bar(vals, pct, color="#cccccc", edgecolor="#999999", width=0.6, label="Null")
        ax.axvline(obs, color=c, linewidth=2.5, linestyle="--",
                   label=f"Observed = {obs}")
        ax.set_title(label.strip(), fontsize=10)
        ax.set_xlabel("Feature overlap count")
        ax.set_ylabel("% of permutations")
        ax.legend(fontsize=9)
        ax.yaxis.set_major_formatter(ticker.PercentFormatter())

    plt.tight_layout()
    plt.savefig("permutation_null_distributions.png", dpi=150, bbox_inches="tight")
    print("\n[plot] Saved → permutation_null_distributions.png")
    plt.show()

# ── CONFIG (edit these) ───────────────────────────────────────────────────────
class args:
    json   = "layer20_crosslinguistic_analysis.json"  # adjust path if needed
    n_perm = 100_000
    top_k  = 100
    n_feat = 131_072
    seed   = 42
    plot   = True  # set False if you don't want the figure

# ── RUN ───────────────────────────────────────────────────────────────────────
print(f"\nLoading feature sets from: {args.json}")
feature_sets = load_feature_sets(args.json, args.top_k)

print("\nObserved overlaps:")
observed = compute_overlaps(feature_sets)
for key, label in LABELS.items():
    print(f"  {label}: {observed[key]}")

null = run_permutation_test(observed, args.n_perm, args.top_k, args.n_feat, args.seed)
print_results(observed, null, args.top_k, args.n_feat, args.n_perm)

if args.plot:
    plot_null_distributions(observed, null)