# -*- coding: utf-8 -*-
"""cross_linguistic_steering_notebook_(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-cetmTEskKblO2SlGj0rb9BwNFP0pjw

# Cross-Linguistic Steering Experiment: Slang Features Across Languages

## Overview
This notebook tests **cross-linguistic steering** using SAE features discovered in Layer 20 of Gemma-2-9B-IT.

### Experimental Design:
1. **Cross-Language Steering**: Use features from Language A to steer sentences in Language B/C
2. **Universal Features**: Use features found in ALL 3 languages to steer each language
3. **Same-Language Baseline**: Use each language's own features for comparison

### Alpha Values Tested:
`[-200, -150, -100, -50, 0, 50, 100, 150, 200, 350, 400, 700]`

### Evaluation:
Formality scores (0-1) using GPT-4o (LLM as a judge)
"""

# Install required packages
!pip install -q sae-lens transformer-lens transformers scipy pandas matplotlib seaborn tqdm openai
!pip uninstall numpy -y
!pip install numpy==1.26.4 -q
!pip install --force-reinstall pandas -q

import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from tqdm import tqdm
from functools import partial
from transformers import AutoTokenizer, AutoModelForCausalLM  # For Gemma
from itertools import product
import warnings
import os
from openai import OpenAI
warnings.filterwarnings('ignore')


print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

from huggingface_hub import login
login()

"""## 1. Load Model and SAE"""

from sae_lens import SAE
import transformer_lens

print("Loading Gemma 9B IT model with TransformerLens...")
print("This will take a few minutes...")

tl_model = transformer_lens.HookedTransformer.from_pretrained(
    "google/gemma-2-9b-it",
    device="cuda",
    dtype=torch.bfloat16,
)

print("Model loaded successfully!")
print(f"Model has {tl_model.cfg.n_layers} layers")
print(f"Model dimension: {tl_model.cfg.d_model}")

print("Loading SAE from Gemma Scope (Layer 20)...")

sae, cfg_dict, sparsity = SAE.from_pretrained(
    release="gemma-scope-9b-it-res-canonical",
    sae_id="layer_20/width_131k/canonical",  # Using 131k width for layer 20 features
    device="cuda"
)

print(f"SAE loaded successfully!")
print(f"SAE width: {sae.cfg.d_sae}")
print(f"SAE input dimension: {sae.cfg.d_in}")

"""## 2. Define Language-Specific Feature Sets

Based on cross-linguistic analysis from Layer 20 slang detection experiments.
"""

print("="*80)
print("DEFINING LANGUAGE-SPECIFIC AND UNIVERSAL FEATURE SETS - LAYER 20")
print("="*80)

# ============================================================================
# UNIVERSAL FEATURES (All 3 Languages - Layer 20)
# These 10 features appear in top-100 for ALL 3 languages
# ============================================================================
UNIVERSAL_FEATURES = [
    # --- TIER 1: The "Slang Context" Headers (Active for >50% of all terms) ---
    3249,   # The King: 77.8% coverage across 3 languages. (+42.6% avg diff)
    2870,   # 55.6% coverage. (+23.3% avg diff)
    7789,   # 53.1% coverage. (+18.8% avg diff)
    667,    # 51.9% coverage. (+19.7% avg diff)

    # --- TIER 2: High Consistency (>30% coverage) ---
    3375,   # 45.7% coverage
    14220,  # 45.7% coverage (+20.3% avg diff)
    16354,  # 40.7% coverage (+19.4% avg diff)
    8515,   # 38.3% coverage (+17.1% avg diff)
    12662,  # 35.8% coverage (+15.1% avg diff)
    3542,   # 29.6% coverage (+16.8% avg diff)
    35440,   # Avg Diff: +33.6% (Eng: +52.1%, Heb: +21.3%, Rus: +27.4%)
    93521,   # Avg Diff: +31.6% (Eng: +39.7%, Heb: +13.0%, Rus: +42.0%)
    97003,   # Avg Diff: +21.2% (Eng: +12.8%, Heb: +12.8%, Rus: +38.0%)
    33236,   # Avg Diff: +20.0% (Eng: +43.7%, Heb: +9.8%, Rus: +6.3%)
    88782,   # Avg Diff: +14.7% (Eng: +17.0%, Heb: +6.6%, Rus: +20.7%)
    92777,   # Avg Diff: +11.0% (Eng: +5.6%, Heb: +6.3%, Rus: +21.0%)
    20069,   # Avg Diff: +10.5% (Eng: +10.4%, Heb: +9.8%, Rus: +11.4%)
    71479,   # Avg Diff: +10.1% (Eng: +7.8%, Heb: +6.2%, Rus: +16.2%)
    24006,   # Avg Diff: +9.6%  (Eng: +5.2%, Heb: +4.5%, Rus: +19.1%)
    46374,   # Avg Diff: +9.2%  (Eng: +15.3%, Heb: +6.2%, Rus: +6.1%)
]

# ============================================================================
# ENGLISH TOP FEATURES (Top 10 discriminative for English slang)
# ============================================================================
ENGLISH_FEATURES = [
    35440,   # +52.1% diff (Slang: 59.9%, Lit: 7.8%)
    33236,   # +43.7% diff (Slang: 45.9%, Lit: 2.1%)
    93521,   # +39.7% diff (Slang: 40.7%, Lit: 1.0%)
    7697,    # +18.7% diff (Slang: 36.0%, Lit: 17.3%)
    108864,  # +18.6% diff (Slang: 25.8%, Lit: 7.2%)
    21876,   # +17.8% diff (Slang: 20.2%, Lit: 2.4%)
    28165,   # +17.2% diff (Slang: 40.3%, Lit: 23.1%)
    40141,   # +17.1% diff (Slang: 42.1%, Lit: 25.0%)
    88782,   # +17.0% diff (Slang: 17.3%, Lit: 0.3%)
    103326,  # +16.3% diff (Slang: 18.6%, Lit: 2.4%)
]




# ============================================================================
# HEBREW TOP FEATURES (Top 10 discriminative for Hebrew slang)
# ============================================================================
HEBREW_FEATURES = [
    115163,  # +22.0% diff (Slang: 51.6%, Lit: 29.6%)
    35440,   # +21.3% diff (Slang: 24.0%, Lit: 2.8%)
    74327,   # +14.5% diff (Slang: 71.1%, Lit: 56.5%)
    93521,   # +13.0% diff (Slang: 13.3%, Lit: 0.3%)
    97003,   # +12.8% diff (Slang: 16.7%, Lit: 3.9%)
    30218,   # +12.5% diff (Slang: 45.6%, Lit: 33.1%)
    7163,    # +12.4% diff (Slang: 13.1%, Lit: 0.7%)
    8408,    # +11.3% diff (Slang: 17.0%, Lit: 5.7%)
    104622,  # +10.5% diff (Slang: 23.5%, Lit: 13.0%)
    86719,   # +10.4% diff (Slang: 48.4%, Lit: 38.0%)
]

# ============================================================================
# RUSSIAN TOP FEATURES (Top 10 discriminative for Russian slang)
# ============================================================================
RUSSIAN_FEATURES = [
    93521,   # +42.0% diff (Slang: 43.0%, Lit: 1.0%)
    97003,   # +38.0% diff (Slang: 39.7%, Lit: 1.7%)
    115163,  # +37.4% diff (Slang: 46.5%, Lit: 9.0%)
    45410,   # +29.5% diff (Slang: 37.3%, Lit: 7.8%)
    35440,   # +27.4% diff (Slang: 28.7%, Lit: 1.3%)
    83575,   # +21.3% diff (Slang: 23.7%, Lit: 2.4%)
    92777,   # +21.0% diff (Slang: 21.3%, Lit: 0.3%)
    88782,   # +20.7% diff (Slang: 21.2%, Lit: 0.6%)
    3598,    # +19.2% diff (Slang: 21.3%, Lit: 2.2%)
    24006,   # +19.1% diff (Slang: 27.5%, Lit: 8.4%)
]

# HEBREW + RUSSIAN (Excluding English)
# Shared by Hebrew and Russian; negligible or negative impact in English
HEBREW_RUSSIAN_EXCLUSIVE = [
    115163,  # +29.7% pair avg (Heb: +22.0%, Rus: +37.4%, Eng: -0.0%)
    45410,   # +17.6% pair avg (Heb: +5.8%, Rus: +29.5%, Eng: -13.4%)
    8408,    # +13.8% pair avg (Heb: +11.3%, Rus: +16.2%, Eng: +0.7%)
    30218,   # +13.7% pair avg (Heb: +12.5%, Rus: +14.8%, Eng: +0.2%)
    46695,   # +11.2% pair avg (Heb: +7.5%, Rus: +14.9%, Eng: +0.0%)
    104622,  # +10.4% pair avg (Heb: +10.5%, Rus: +10.3%, Eng: -0.1%)
    51811,   # +9.1% pair avg  (Heb: +8.4%, Rus: +9.9%, Eng: -0.3%)
    39066,   # +8.1% pair avg  (Heb: +4.4%, Rus: +11.9%, Eng: +0.2%)
    105496,  # +7.9% pair avg  (Heb: +9.3%, Rus: +6.6%, Eng: +1.1%)
    46769,   # +7.8% pair avg  (Heb: +8.7%, Rus: +6.9%, Eng: +1.0%)
    98848,   # +7.4% pair avg  (Heb: +3.4%, Rus: +11.4%, Eng: +0.0%)
    72807,   # +5.1% pair avg  (Heb: +3.4%, Rus: +6.8%, Eng: +3.9%)
    122872,  # +5.0% pair avg  (Heb: +3.9%, Rus: +6.0%, Eng: +0.0%)
]

# HEBREW + ENGLISH (Excluding Russian)
# Shared by Hebrew and English; negligible or negative impact in Russian
HEBREW_ENGLISH_EXCLUSIVE = [
    85416,   # +9.0% pair avg  (Heb: +4.5%, Eng: +13.6%, Rus: -6.4%)
    47814,   # +8.3% pair avg  (Heb: +3.4%, Eng: +13.3%, Rus: +0.1%)
    23902,   # +6.6% pair avg  (Heb: +6.2%, Eng: +7.0%, Rus: +0.8%)
    61806,   # +6.6% pair avg  (Heb: +4.5%, Eng: +8.7%, Rus: +0.8%)
    98997,   # +5.5% pair avg  (Heb: +5.2%, Eng: +5.9%, Rus: +2.5%)
]

# ENGLISH + RUSSIAN (Excluding Hebrew)
# Shared by English and Russian; negligible or negative impact in Hebrew
ENGLISH_RUSSIAN_EXCLUSIVE = [
    21876,   # +14.5% pair avg (Eng: +17.8%, Rus: +11.3%, Heb: +1.7%)
    93245,   # +14.4% pair avg (Eng: +16.1%, Rus: +12.8%, Heb: +0.8%)
    129197,  # +10.7% pair avg (Eng: +14.4%, Rus: +7.0%, Heb: +2.7%)
    27619,   # +9.6% pair avg  (Eng: +10.1%, Rus: +9.1%, Heb: +0.5%)
    107295,  # +8.5% pair avg  (Eng: +10.4%, Rus: +6.5%, Heb: -2.3%)
    128449,  # +7.6% pair avg  (Eng: +7.8%, Rus: +7.4%, Heb: +1.9%)
    73106,   # +6.8% pair avg  (Eng: +7.9%, Rus: +5.7%, Heb: +0.2%)
    67248,   # +6.5% pair avg  (Eng: +7.8%, Rus: +5.2%, Heb: +2.4%)
    70055,   # +6.1% pair avg  (Eng: +6.1%, Rus: +6.2%, Heb: +2.6%)
    68324,   # +5.9% pair avg  (Eng: +5.8%, Rus: +6.1%, Heb: +0.3%)
    111712,  # +5.6% pair avg  (Eng: +4.7%, Rus: +6.5%, Heb: +1.3%)
]

# Store in dictionary for easy access
FEATURE_SETS = {
    'universal': UNIVERSAL_FEATURES,
    'english': ENGLISH_FEATURES,
    'hebrew': HEBREW_FEATURES,
    'russian': RUSSIAN_FEATURES,
    'heb_rus_excl': HEBREW_RUSSIAN_EXCLUSIVE,
    'heb_eng_excl': HEBREW_ENGLISH_EXCLUSIVE,
    'eng_rus_excl': ENGLISH_RUSSIAN_EXCLUSIVE,
}

print("\nFeature Sets Defined (Layer 20):")
for name, features in FEATURE_SETS.items():
    print(f"  {name.upper():12s}: {len(features)} features - {features[:5]}...")

print(f"\n✓ Total unique features across all sets: {len(set(sum(FEATURE_SETS.values(), [])))}")

"""## 3. Extract Steering Vectors"""

print("="*80)
print("EXTRACTING STEERING VECTORS FROM DISCOVERED FEATURES")
print("="*80)

decoder_weights = sae.W_dec.data
print(f"Decoder matrix shape: {decoder_weights.shape}")

# Create steering vectors for each feature set
steering_vectors = {}

for set_name, features in FEATURE_SETS.items():
    # Get vectors for all features in this set
    feature_vectors = []
    for feat_idx in features:
        if feat_idx < decoder_weights.shape[0]:
            feature_vectors.append(decoder_weights[feat_idx].clone())
        else:
            print(f"  Warning: Feature {feat_idx} out of bounds, skipping")

    if feature_vectors:
        # Create mean vector from all features
        mean_vector = torch.stack(feature_vectors).mean(dim=0)
        # Normalize
        mean_vector = mean_vector / mean_vector.norm()
        steering_vectors[set_name] = mean_vector
        print(f"  {set_name.upper():12s} vector created (norm: {mean_vector.norm():.4f})")

print(f"\n✓ Created {len(steering_vectors)} steering vectors")

"""## 4. Define Target Sentences in All Languages"""

print("="*80)
print("DEFINING TARGET SENTENCES IN ALL LANGUAGES")
print("="*80)

# ============================================================================
# ENGLISH SENTENCES (mix of formal/neutral openings)
# ============================================================================
ENGLISH_SENTENCES = [
    "I think that",
    "She believes the new restaurant downtown",
    "In my opinion, the movie was",
    "They feel like the music",
    "The exam results were",
    "The presentation was",
    "The game last night was",
    "The outfit she wore looked",
    "The book I finished was",
    "The car he bought seems",
    "I feel that the concert was",
    "The coffee from that shop tastes",
    "The new phone features are",
    "The vacation we took was",
    "He thought his explanation was",
    "Yo, that party was",
    "Bro, check out this",
    "That beat is so",
    "Dude, the game last night was",
    "Man, this food is",
]

# ============================================================================
# HEBREW SENTENCES (mix of formal/neutral openings)
# ============================================================================
HEBREW_SENTENCES = [
        "אני חושב ש",
        "היא מאמינה שהמסעדה החדשה במרכז העיר",
        "לדעתי, הסרט היה",
        "הם מרגישים שהמוזיקה",
        "תוצאות המבחן היו",
        "המצגת הייתה",
        "המשחק אמש היה",
        "הבגד שהיא לבשה נראה",
        "הספר שסיימתי היה",
        "המכונית שהוא קנה נראית",
        "אני מרגיש שהקונצרט היה",
        "הקפה מהחנות ההיא טעים",
        "התכונות של הטלפון החדש הן",
        "החופשה שלקחנו הייתה",
        "הוא חשב שההסבר שלו היה",
        "יו, המסיבה הייתה",
        "אחי, תבדוק את זה",
        "הביט הזה כל כך",
        "גבר, המשחק אמש היה",
        "אחי, האוכל הזה",
        "הלוק שלה נראה",
        "האווירה פה היא",
        "השיר הזה פשוט",
        "החוויה הזאת הייתה ממש",
        "הפגישה היום הייתה",
        "הדבר החדש הזה",
        "כל המצב הזה",
        "הכל בזה היה",
    ]

# ============================================================================
# RUSSIAN SENTENCES (mix of formal/neutral openings)
# ============================================================================
RUSSIAN_SENTENCES = [
        "Я думаю, что",
        "Она считает, что новый ресторан в центре города",
        "По моему мнению, фильм был",
        "Они чувствуют, что музыка",
        "Результаты экзамена были",
        "Презентация была",
        "Игра вчера вечером была",
        "Наряд, который она надела, выглядел",
        "Книга, которую я закончил, была",
        "Машина, которую он купил, кажется",
        "Я чувствую, что концерт был",
        "Кофе из того магазина на вкус",
        "Новые функции телефона",
        "Отпуск, который мы взяли, был",
        "Он думал, что его объяснение было",
        "Йо, та вечеринка была",
        "Бро, посмотри на это",
        "Этот бит такой",
        "Чувак, игра вчера была",
        "Мужик, эта еда",
        "Её наряд выглядит",
        "Атмосфера здесь",
        "Этот трек просто",
        "Тот опыт был реально",
        "Встреча сегодня была",
        "Эта новая штука",
        "Вся эта ситуация",
        "Всё в этом было",
    ]

GERMAN_SENTENCES = [
    "Ich denke, dass",
    "Sie glaubt, das neue Restaurant in der Innenstadt",
    "Meiner Meinung nach war der Film",
    "Sie haben das Gefühl, dass die Musik",
    "Die Prüfungsergebnisse waren",
    "Die Präsentation war",
    "Das Spiel gestern Abend war",
    "Das Outfit, das sie trug, sah ... aus",
    "Das Buch, das ich beendet habe, war",
    "Das Auto, das er gekauft hat, scheint",
    "Ich finde, dass das Konzert ... war",
    "Der Kaffee aus diesem Laden schmeckt",
    "Die neuen Telefonfunktionen sind",
    "Der Urlaub, den wir gemacht haben, war",
    "Er dachte, seine Erklärung sei",
    "Yo, diese Party war",
    "Alter, schau dir das mal an",
    "Dieser Beat ist so",
    "Alter, das Spiel gestern Abend war",
    "Mann, dieses Essen ist"
    ]
# Store in dictionary
SENTENCES = {
    'english': ENGLISH_SENTENCES,
    'hebrew': HEBREW_SENTENCES,
    'russian': RUSSIAN_SENTENCES,
    'german' : GERMAN_SENTENCES
}

print("\nSentence Sets Defined:")
for lang, sents in SENTENCES.items():
    print(f"  {lang.upper():12s}: {len(sents)} sentences")

total_sentences = sum(len(s) for s in SENTENCES.values())
print(f"\n✓ Total sentences: {total_sentences}")

"""## 5. Define Steering Functions"""

STEERING_LAYER = 20

def steering_hook(activation, hook, steering_vector, coefficient):
    """Hook function to add steering vector to residual stream."""
    return activation + coefficient * steering_vector.to(activation.device)

def generate_with_steering(prompt, steering_vector, coefficient, max_tokens=50,
                           temperature=0.7, top_p=0.9):
    """Generate text with steering applied."""
    tokens = tl_model.to_tokens(prompt)
    hook_fn = partial(steering_hook, steering_vector=steering_vector, coefficient=coefficient)
    hook_name = f"blocks.{STEERING_LAYER}.hook_resid_post"

    with tl_model.hooks(fwd_hooks=[(hook_name, hook_fn)]):
        output = tl_model.generate(
            tokens,
            max_new_tokens=max_tokens,
            temperature=temperature,
            top_p=top_p,
            do_sample=True if temperature > 0 else False,
        )
    return tl_model.to_string(output[0])

def generate_baseline(prompt, max_tokens=50, temperature=0.7, top_p=0.9):
    """Generate text without steering (baseline)."""
    tokens = tl_model.to_tokens(prompt)
    output = tl_model.generate(
        tokens,
        max_new_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        do_sample=True if temperature > 0 else False,
    )
    return tl_model.to_string(output[0])

def clean_output(full_text, prompt):
    """Clean generated output by removing prompt and special tokens."""
    output = full_text.replace(prompt, "").strip()
    output = output.replace("<bos>", "").replace("<eos>", "")
    output = output.replace("<end_of_turn>", "").replace("<start_of_turn>", "")
    return output.strip()

print("✓ Steering functions defined")
print(f"  Steering layer: {STEERING_LAYER}")

"""## 6. Run Cross-Linguistic Steering Experiments"""

print("="*80)
print("CROSS-LINGUISTIC STEERING EXPERIMENT")
print("="*80)

# Define coefficients
COEFFICIENTS = [-200, -150, -100, -50, 0, 50, 100, 150, 200, 350, 400, 700]

# Define all experimental conditions
# (sentence_language, feature_source)
EXPERIMENTS = [
    # Cross-language steering
    # Universal features on all languages
    ('english', 'universal'),   # Universal features → English sentences
    ('hebrew', 'universal'),    # Universal features → Hebrew sentences
    ('russian', 'universal'),   # Universal features → Russian sentences
    ('german','universal') ,    # Universal features → German sentences
    ('english', 'heb_rus_excl'),   # Hebrew+Russian -English features → English sentences
    ('hebrew', 'eng_rus_excl'),    # Russian+English-Hebrew features → Hebrew sentences
    ('russian', 'heb_eng_excl'),   # English+Hebrew-Russian features → Russian sentences


]

print(f"Coefficients: {COEFFICIENTS}")
print(f"\nExperimental Conditions ({len(EXPERIMENTS)}):")
for sent_lang, feat_src in EXPERIMENTS:
    print(f"  {feat_src.upper():12s} features → {sent_lang.upper():12s} sentences")

# Calculate total generations
total_gens = sum(len(SENTENCES[e[0]]) for e in EXPERIMENTS) * len(COEFFICIENTS)
print(f"\nTotal generations to perform: {total_gens}")

print("="*80)
print("RUNNING ALL STEERING EXPERIMENTS")
print("="*80)

all_results = []
SHOW_EXAMPLES = 3  # Show examples for first N prompts per experiment

for exp_idx, (sentence_lang, feature_source) in enumerate(EXPERIMENTS):
    print(f"\n{'='*70}")
    print(f"EXPERIMENT {exp_idx + 1}/{len(EXPERIMENTS)}: {feature_source.upper()} → {sentence_lang.upper()}")
    print(f"{'='*70}")

    sentences = SENTENCES[sentence_lang]
    steering_vec = steering_vectors[feature_source]

    for prompt_idx, prompt in enumerate(tqdm(sentences, desc=f"{feature_source}→{sentence_lang}")):
        show_this = prompt_idx < SHOW_EXAMPLES

        if show_this:
            print(f"\n  Prompt {prompt_idx + 1}: \"{prompt[:50]}...\"" if len(prompt) > 50 else f"\n  Prompt {prompt_idx + 1}: \"{prompt}\"")

        for coef in COEFFICIENTS:
            try:
                if coef == 0:
                    # Baseline - no steering
                    output_text = generate_baseline(prompt, max_tokens=50)
                else:
                    # Apply steering
                    output_text = generate_with_steering(
                        prompt, steering_vec, coef, max_tokens=50
                    )

                # Clean output
                output_clean = clean_output(output_text, prompt)

                # Store result
                all_results.append({
                    'sentence_language': sentence_lang,
                    'feature_source': feature_source,
                    'experiment_type': 'same_language' if sentence_lang == feature_source else
                                       ('universal' if feature_source == 'universal' else 'cross_language'),
                    'prompt': prompt,
                    'coefficient': coef,
                    'generated_text': output_clean[:300],
                    'full_text': (prompt + " " + output_clean)[:400],
                    'steering_direction': 'formal' if coef < 0 else ('neutral' if coef == 0 else 'slang')
                })

                if show_this:
                    direction = "←FORMAL" if coef < 0 else ("BASELINE" if coef == 0 else "SLANG→")
                    print(f"    [{coef:+4d}] {direction:8s} | {output_clean[:50]}...")

            except Exception as e:
                print(f"  Error at coef {coef}: {e}")

results_df = pd.DataFrame(all_results)
print(f"\n{'='*80}")
print(f"✓ Generated {len(results_df)} completions total")
print(f"{'='*80}")

# Save progress - all results generated so far
progress_df = pd.DataFrame(all_results)
progress_df.to_csv('steering_progress_checkpoint.csv', index=False)

print(f"✓ Saved {len(progress_df)} results to 'steering_progress_checkpoint.csv'")
print(f"\nCompleted experiments:")
for (sent_lang, feat_src) in progress_df.groupby(['sentence_language', 'feature_source']).size().index:
    count = len(progress_df[(progress_df['sentence_language'] == sent_lang) &
                            (progress_df['feature_source'] == feat_src)])
    print(f"  {feat_src} → {sent_lang}: {count} generations")

print(f"\nNext time, start from: EXPERIMENT 4/7: UNIVERSAL → GERMAN")

# Load previous progress and continue from German
import pandas as pd

# Load checkpoint
checkpoint_df = pd.read_csv('steering_progress_checkpoint.csv')
all_results = checkpoint_df.to_dict('records')
print(f"✓ Loaded {len(all_results)} previous results")

# Define remaining experiments (starting from German)
REMAINING_EXPERIMENTS = [
    ('german', 'universal'),
    ('english', 'heb_rus_excl'),
    ('hebrew', 'eng_rus_excl'),
    ('russian', 'heb_eng_excl'),
]

print("="*80)
print("RUNNING ALL STEERING REMAINING_EXPERIMENTS")
print("="*80)

SHOW_EXAMPLES = 3  # Show examples for first N prompts per experiment

for exp_idx, (sentence_lang, feature_source) in enumerate(REMAINING_EXPERIMENTS):
    print(f"\n{'='*70}")
    print(f"EXPERIMENT {exp_idx + 1}/{len(REMAINING_EXPERIMENTS)}: {feature_source.upper()} → {sentence_lang.upper()}")
    print(f"{'='*70}")

    sentences = SENTENCES[sentence_lang]
    steering_vec = steering_vectors[feature_source]

    for prompt_idx, prompt in enumerate(tqdm(sentences, desc=f"{feature_source}→{sentence_lang}")):
        show_this = prompt_idx < SHOW_EXAMPLES

        if show_this:
            print(f"\n  Prompt {prompt_idx + 1}: \"{prompt[:50]}...\"" if len(prompt) > 50 else f"\n  Prompt {prompt_idx + 1}: \"{prompt}\"")

        for coef in COEFFICIENTS:
            try:
                if coef == 0:
                    # Baseline - no steering
                    output_text = generate_baseline(prompt, max_tokens=50)
                else:
                    # Apply steering
                    output_text = generate_with_steering(
                        prompt, steering_vec, coef, max_tokens=50
                    )

                # Clean output
                output_clean = clean_output(output_text, prompt)

                # Store result
                all_results.append({
                    'sentence_language': sentence_lang,
                    'feature_source': feature_source,
                    'experiment_type': 'same_language' if sentence_lang == feature_source else
                                       ('universal' if feature_source == 'universal' else 'cross_language'),
                    'prompt': prompt,
                    'coefficient': coef,
                    'generated_text': output_clean[:300],
                    'full_text': (prompt + " " + output_clean)[:400],
                    'steering_direction': 'formal' if coef < 0 else ('neutral' if coef == 0 else 'slang')
                })

                if show_this:
                    direction = "←FORMAL" if coef < 0 else ("BASELINE" if coef == 0 else "SLANG→")
                    print(f"    [{coef:+4d}] {direction:8s} | {output_clean[:50]}...")

            except Exception as e:
                print(f"  Error at coef {coef}: {e}")

results_df = pd.DataFrame(all_results)
print(f"\n{'='*80}")
print(f"✓ Generated {len(results_df)} completions total")
print(f"{'='*80}")

# Save progress - all results generated so far
progress_df = pd.DataFrame(all_results)
progress_df.to_csv('steering_progress_checkpoint.csv', index=False)

print(f"✓ Saved {len(progress_df)} results to 'steering_progress_checkpoint.csv'")
print(f"\nCompleted experiments:")
for (sent_lang, feat_src) in progress_df.groupby(['sentence_language', 'feature_source']).size().index:
    count = len(progress_df[(progress_df['sentence_language'] == sent_lang) &
                            (progress_df['feature_source'] == feat_src)])
    print(f"  {feat_src} → {sent_lang}: {count} generations")

# Examine the checkpoint CSV
import pandas as pd

df = pd.read_csv('steering_progress_checkpoint.csv')

print(f"Total rows: {len(df)}")
print(f"Columns: {list(df.columns)}")
print(f"\n" + "="*50)
print("Experiments completed:")
print(df.groupby(['sentence_language', 'feature_source']).size().to_string())
print(f"\n" + "="*50)
print("Coefficients used:", sorted(df['coefficient'].unique()))
print(f"\n" + "="*50)
print("\nSample rows:")
df.head(3)

"""## 7. call GPT via API"""

print("Setting up GPT-4o as formality judge...")

# Initialize OpenAI client
client = OpenAI(api_key="YOUR_API_KEY_HERE")

import time
import re

def get_formality_scores_batch(texts, batch_size=10, max_retries=3):
    """
    Use GPT-4o to rate formality for multiple texts at once.
    Returns a list of scores (0-1) corresponding to input texts.
    """
    all_scores = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        batch_scores = _process_batch(batch, max_retries)
        all_scores.extend(batch_scores)

        # Small delay to avoid rate limits
        if i + batch_size < len(texts):
            time.sleep(0.5)

    return all_scores

def _process_batch(texts, max_retries=3):
    """Process a single batch of texts."""
    # Filter out empty texts, keep track of indices
    valid_indices = []
    valid_texts = []
    results = [None] * len(texts)  # Default scores

    for idx, text in enumerate(texts):
        if text and len(str(text).strip()) >= 3:
            valid_indices.append(idx)
            valid_texts.append(str(text)[:300])  # Truncate to save tokens

    if not valid_texts:
        return results

    # Build batch prompt - simpler format, no markers
    texts_formatted = "\n".join([f"{i+1}. \"{t}\"" for i, t in enumerate(valid_texts)])

    prompt = f"""Rate the formality of each text below on a scale from 0 to 1.
- 0 = very informal, casual, slang, colloquial
- 1 = very formal, professional, academic

Return ONLY a JSON array of numbers, nothing else. Example: [0.2, 0.8, 0.5]
respond in the following structure: [CLASSIFICATION_START]your score[CLASSIFICATION_END]

Texts:
{texts_formatted}"""

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",  # Using mini for cost savings
                messages=[
                    {"role": "system", "content": "You are a formality scorer. Return only a JSON array of numbers between 0 and 1."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=10 * len(valid_texts),
                temperature=0
            )
            response_text = response.choices[0].message.content.strip()

            # Extract JSON array - handle markdown code blocks
            response_text = response_text.replace('```json', '').replace('```', '').strip()

            # Find array in response
            match = re.search(r'\[[\d\.,\s]+\]', response_text)
            if match:
                import json
                scores = json.loads(match.group())

                # Map back to original indices
                for idx, score in zip(valid_indices, scores):
                    if idx < len(results):
                        results[idx] = min(max(0, float(score)), 1)
                return results
            else:
                raise ValueError(f"No JSON array found in: {response_text}")

        except Exception as e:
            if attempt == max_retries - 1:
                print(f"Warning: Batch failed: {e}")
            else:
                time.sleep(1)  # Wait before retry

    return results

def get_formality_score_gpt4o(text, max_retries=3):
    """Single text scoring (for compatibility). Use batch version when possible."""
    return get_formality_scores_batch([text], batch_size=1, max_retries=max_retries)[0]

print("✓ GPT-4o formality judge ready (batched)")

# Test GPT-4o formality judge
print("Testing GPT-4o formality judge...")
test_texts = [
    ("That party was lit, fam!", "English slang"),
    ("The house was set on fire by a terror group.", "English formal"),
    ("זה היה אש!", "Hebrew slang"),
    ("האירוע היה מאוד מוצלח.", "Hebrew formal"),
    ("Это было круто!", "Russian slang"),
    ("Мероприятие было очень успешным.", "Russian formal"),
]

print("\nFormality Scores (0=informal, 1=formal):")
for text, desc in test_texts:
    score = get_formality_score_gpt4o(text)
    print(f"  [{score:.3f}] {desc:15s}: {text}")

print("="*80)
print("FILTERING OUT NON-TARGET LANGUAGE OUTPUTS")
print("="*80)

import re

def detect_language(text):
    """
    Detect if text is primarily in English, Hebrew, Russian, or other.
    Returns: 'english', 'hebrew', 'russian', or 'other'
    """
    if pd.isna(text) or not text or len(str(text).strip()) == 0:
              return 'other'

    # Count character types
    hebrew_chars = len(re.findall(r'[\u0590-\u05FF]', text))
    russian_chars = len(re.findall(r'[\u0400-\u04FF]', text))
    latin_chars = len(re.findall(r'[a-zA-Z]', text))

    # Other scripts (Hindi, Arabic, Chinese, etc.)
    devanagari_chars = len(re.findall(r'[\u0900-\u097F]', text))  # Hindi
    arabic_chars = len(re.findall(r'[\u0600-\u06FF]', text))
    chinese_chars = len(re.findall(r'[\u4E00-\u9FFF]', text))
    japanese_chars = len(re.findall(r'[\u3040-\u309F\u30A0-\u30FF]', text))
    korean_chars = len(re.findall(r'[\uAC00-\uD7AF]', text))
    thai_chars = len(re.findall(r'[\u0E00-\u0E7F]', text))

    other_script_chars = devanagari_chars + arabic_chars + chinese_chars + japanese_chars + korean_chars + thai_chars

    total_alpha = hebrew_chars + russian_chars + latin_chars + other_script_chars

    if total_alpha == 0:
        return 'other'

    # If significant other script presence, mark as other
    if other_script_chars / total_alpha > 0.3:
        return 'other'

    # Determine primary language
    if hebrew_chars / total_alpha > 0.4:
        return 'hebrew'
    elif russian_chars / total_alpha > 0.4:
        return 'russian'
    elif latin_chars / total_alpha > 0.4:
        return 'latin'
    else:
        return 'other'
valid_df = results_df.copy()
# Detect language for each output
print("Detecting output languages...")
valid_df['detected_language'] = valid_df['generated_text'].apply(detect_language)

# Count before filtering
lang_counts = valid_df['detected_language'].value_counts()
print(f"\nDetected languages (before filtering):")
for lang, count in lang_counts.items():
    print(f"  {lang}: {count} ({100*count/len(valid_df):.1f}%)")

# Keep only valid languages (English, Hebrew, Russian)
valid_languages = ['english', 'hebrew', 'russian','german','latin']
before_count = len(valid_df)
valid_df = valid_df[valid_df['detected_language'].isin(valid_languages)].copy()
after_count = len(valid_df)

print(f"\n✓ Filtered out {before_count - after_count} non-target language outputs")
print(f"✓ Remaining: {after_count} outputs")

# Show breakdown by experiment
print(f"\nRemaining outputs by experiment:")
for (sent_lang, feat_src) in EXPERIMENTS:
    count = len(valid_df[(valid_df['sentence_language'] == sent_lang) &
                         (valid_df['feature_source'] == feat_src)])
    print(f"  {feat_src:18s} → {sent_lang:12s}: {count} outputs")

print("="*80)
print("SCORING FORMALITY WITH GPT-4o")
print("="*80)

import json
import time

# Get all texts to score
all_texts = valid_df['generated_text'].tolist()
print(f"Total texts to score: {len(all_texts)}")

# Process in batches
BATCH_SIZE = 15
all_scores = []

total_batches = (len(all_texts) + BATCH_SIZE - 1) // BATCH_SIZE
print(f"Processing {total_batches} batches of up to {BATCH_SIZE} texts each...")

for batch_idx in tqdm(range(0, len(all_texts), BATCH_SIZE), desc="GPT-4o scoring"):
    batch_end = min(batch_idx + BATCH_SIZE, len(all_texts))
    batch_texts = all_texts[batch_idx:batch_end]

    batch_scores = get_formality_scores_batch(batch_texts, batch_size=len(batch_texts))
    all_scores.extend(batch_scores)

    time.sleep(0.5)  # Rate limit delay

# Add scores to dataframe
valid_df['formality_score'] = all_scores
valid_df['scoring_method'] = 'gpt4o'

# Drop failed scores
before_drop = len(valid_df)
valid_df = valid_df[valid_df['formality_score'].notna()]
after_drop = len(valid_df)

if before_drop > after_drop:
    print(f"\nDropped {before_drop - after_drop} rows with failed scoring")

print(f"\n✓ Scored {len(valid_df)} outputs with GPT-4o")
print(f"\nFormality score distribution:")
print(valid_df['formality_score'].describe())

"""## 9. Analysis: Overall Correlation"""

print("="*80)
print("OVERALL CORRELATION ANALYSIS")
print("="*80)

# Overall correlation
correlation, p_value = stats.pearsonr(valid_df['coefficient'], valid_df['formality_score'])
spearman_corr, spearman_p = stats.spearmanr(valid_df['coefficient'], valid_df['formality_score'])

print(f"\nOverall (all experiments combined):")
print(f"  Pearson Correlation:  r = {correlation:.4f}, p = {p_value:.2e}")
print(f"  Spearman Correlation: ρ = {spearman_corr:.4f}, p = {spearman_p:.2e}")

if correlation < 0:
    print(f"\n  → NEGATIVE correlation: Higher steering → LOWER formality (more slang)")
else:
    print(f"\n  → POSITIVE correlation: Higher steering → HIGHER formality")

"""## 10. Analysis: By Experiment Type"""

print("="*80)
print("CORRELATION BY EXPERIMENT TYPE")
print("="*80)

experiment_stats = []

for exp_type in valid_df['experiment_type'].unique():
    subset = valid_df[valid_df['experiment_type'] == exp_type]
    if len(subset) > 10:
        corr, p_val = stats.pearsonr(subset['coefficient'], subset['formality_score'])
        experiment_stats.append({
            'experiment_type': exp_type,
            'n_samples': len(subset),
            'correlation': corr,
            'p_value': p_val,
            'mean_formality': subset['formality_score'].mean(),
            'std_formality': subset['formality_score'].std(),
        })

exp_stats_df = pd.DataFrame(experiment_stats)
print("\nCorrelation by Experiment Type:")
print(exp_stats_df.to_string(index=False))

print("="*80)
print("CORRELATION BY SPECIFIC EXPERIMENT")
print("="*80)

specific_stats = []

for (sent_lang, feat_src) in EXPERIMENTS:
    subset = valid_df[(valid_df['sentence_language'] == sent_lang) &
                      (valid_df['feature_source'] == feat_src)]
    if len(subset) > 10:
        corr, p_val = stats.pearsonr(subset['coefficient'], subset['formality_score'])
        specific_stats.append({
            'sentence_lang': sent_lang,
            'feature_source': feat_src,
            'n_samples': len(subset),
            'correlation': corr,
            'p_value': p_val,
            'mean_formality': subset['formality_score'].mean(),
        })

specific_df = pd.DataFrame(specific_stats)
print("\nCorrelation by Feature Source → Sentence Language:")
print(specific_df.to_string(index=False))

"""## 11. Analysis: Group Comparisons"""

print("="*80)
print("GROUP COMPARISONS: FORMAL vs BASELINE vs SLANG")
print("="*80)

def analyze_groups(df, label):
    """Analyze formal vs baseline vs slang steering."""
    formal = df[df['coefficient'] < 0]['formality_score']
    baseline = df[df['coefficient'] == 0]['formality_score']
    slang = df[df['coefficient'] > 0]['formality_score']

    print(f"\n{label}:")
    print(f"  Formal steering (coef < 0):  mean = {formal.mean():.4f} ± {formal.std():.4f} (n={len(formal)})")
    print(f"  Baseline (coef = 0):         mean = {baseline.mean():.4f} ± {baseline.std():.4f} (n={len(baseline)})")
    print(f"  Slang steering (coef > 0):   mean = {slang.mean():.4f} ± {slang.std():.4f} (n={len(slang)})")

    if len(formal) > 0 and len(slang) > 0:
        t_stat, t_pvalue = stats.ttest_ind(formal, slang)
        print(f"  T-test (Formal vs Slang): t = {t_stat:.4f}, p = {t_pvalue:.2e}")

        # Effect size
        n1, n2 = len(formal), len(slang)
        pooled_std = np.sqrt(((n1-1)*formal.var() + (n2-1)*slang.var()) / (n1+n2-2))
        cohens_d = (formal.mean() - slang.mean()) / pooled_std if pooled_std > 0 else 0
        print(f"  Effect Size (Cohen's d): {cohens_d:.4f}")

    return formal.mean(), baseline.mean() if len(baseline) > 0 else None, slang.mean()

# Overall
analyze_groups(valid_df, "OVERALL")

# By experiment type
for exp_type in ['same_language', 'cross_language', 'universal']:
    subset = valid_df[valid_df['experiment_type'] == exp_type]
    if len(subset) > 0:
        analyze_groups(subset, f"{exp_type.upper().replace('_', ' ')}")

print("="*80)
print("CROSS-LINGUISTIC TRANSFER EFFECTIVENESS")
print("="*80)

# Compare same-language vs cross-language effectiveness
results_summary = []

for sent_lang in ['english', 'hebrew', 'russian','german']:
    print(f"\n{sent_lang.upper()} Sentences:")
    print("-" * 50)

    for feat_src in FEATURE_SETS.keys():
        subset = valid_df[(valid_df['sentence_language'] == sent_lang) &
                          (valid_df['feature_source'] == feat_src)]

        if len(subset) > 0:
            formal = subset[subset['coefficient'] < 0]['formality_score'].mean()
            slang = subset[subset['coefficient'] > 0]['formality_score'].mean()
            effect = formal - slang if not np.isnan(formal) and not np.isnan(slang) else 0

            transfer_type = 'SAME' if sent_lang == feat_src else ('UNIVERSAL' if feat_src == 'universal' else 'CROSS')

            print(f"  {feat_src:12s} features: formal={formal:.3f}, slang={slang:.3f}, effect={effect:+.3f} [{transfer_type}]")

            results_summary.append({
                'sentence_language': sent_lang,
                'feature_source': feat_src,
                'transfer_type': transfer_type,
                'formal_mean': formal,
                'slang_mean': slang,
                'effect_size': effect,
            })

summary_df = pd.DataFrame(results_summary)
print("\n" + "="*80)
print("SUMMARY TABLE")
print(summary_df.to_string(index=False))

# ============================================================================
# NEW: UNIVERSAL vs PAIR-WITHOUT-LANGUAGE COMPARISON
# ============================================================================
print("\n" + "="*80)
print("UNIVERSAL vs PAIR-EXCLUSION COMPARISON")
print("="*80)
print("Comparing: Universal features vs Pair features that EXCLUDE the target language")
print("-" * 80)

# Mapping: language -> pair that excludes it
exclusion_map = {
    'english': 'heb_rus_excl',   # Hebrew+Russian excludes English
    'hebrew': 'eng_rus_excl',    # English+Russian excludes Hebrew
    'russian': 'heb_eng_excl',   # Hebrew+English excludes Russian
}

comparison_results = []

for sent_lang, excl_pair in exclusion_map.items():
    # Get universal results for this language
    universal_subset = valid_df[(valid_df['sentence_language'] == sent_lang) &
                                 (valid_df['feature_source'] == 'universal')]

    # Get exclusion pair results for this language
    excl_subset = valid_df[(valid_df['sentence_language'] == sent_lang) &
                           (valid_df['feature_source'] == excl_pair)]

    if len(universal_subset) > 0 and len(excl_subset) > 0:
        # Universal stats
        univ_formal = universal_subset[universal_subset['coefficient'] < 0]['formality_score'].mean()
        univ_slang = universal_subset[universal_subset['coefficient'] > 0]['formality_score'].mean()
        univ_effect = univ_formal - univ_slang

        # Exclusion pair stats
        excl_formal = excl_subset[excl_subset['coefficient'] < 0]['formality_score'].mean()
        excl_slang = excl_subset[excl_subset['coefficient'] > 0]['formality_score'].mean()
        excl_effect = excl_formal - excl_slang

        # Difference
        effect_diff = univ_effect - excl_effect

        print(f"\n{sent_lang.upper()} sentences:")
        print(f"  UNIVERSAL features:     formal={univ_formal:.3f}, slang={univ_slang:.3f}, effect={univ_effect:+.3f}")
        print(f"  {excl_pair.upper():18s}: formal={excl_formal:.3f}, slang={excl_slang:.3f}, effect={excl_effect:+.3f}")
        print(f"  → Difference (Universal - Exclusion): {effect_diff:+.3f}")

        if effect_diff > 0:
            print(f"    ✓ Universal features MORE effective for {sent_lang}")
        elif effect_diff < 0:
            print(f"    ✗ Exclusion pair MORE effective for {sent_lang} (unexpected!)")
        else:
            print(f"    = No difference")

        comparison_results.append({
            'sentence_language': sent_lang,
            'universal_effect': univ_effect,
            'exclusion_pair': excl_pair,
            'exclusion_effect': excl_effect,
            'difference': effect_diff,
        })

if comparison_results:
    print("\n" + "-" * 80)
    comp_df = pd.DataFrame(comparison_results)
    print("\nCOMPARISON SUMMARY:")
    print(comp_df.to_string(index=False))

    avg_diff = comp_df['difference'].mean()
    print(f"\nAverage difference (Universal - Exclusion): {avg_diff:+.3f}")
    if avg_diff > 0:
        print("→ Universal features generally MORE effective than exclusion pairs")
    else:
        print("→ Exclusion pairs generally MORE effective than universal features")

"""## 12. Visualizations"""

# Figure 1: Overall effect by coefficient
plot_df = valid_df[(valid_df['coefficient'] >= -200) & (valid_df['coefficient'] <= 200)]
fig, axes = plt.subplots(2, 2, figsize=(14, 12))

# 1. Box plot by coefficient
ax1 = axes[0, 0]
plot_df.boxplot(column='formality_score', by='coefficient', ax=ax1)
ax1.set_xlabel('Steering Coefficient')
ax1.set_ylabel('Formality Score')
ax1.set_title('Formality by Steering Coefficient (All Experiments)')
ax1.axhline(y=0.5, color='r', linestyle='--', alpha=0.5)
plt.suptitle('')

# 2. Line plot with error bars
ax2 = axes[0, 1]
mean_by_coef = plot_df.groupby('coefficient')['formality_score'].agg(['mean', 'std'])
ax2.errorbar(mean_by_coef.index, mean_by_coef['mean'], yerr=mean_by_coef['std'],
             marker='o', capsize=5, linewidth=2, markersize=8)
ax2.axhline(y=0.5, color='r', linestyle='--', alpha=0.5)
ax2.axvline(x=0, color='gray', linestyle=':', alpha=0.5)
ax2.set_xlabel('Steering Coefficient')
ax2.set_ylabel('Mean Formality Score')
ax2.set_title('Mean Formality vs Steering Coefficient')
ax2.grid(True, alpha=0.3)

# 3. By experiment type
ax3 = axes[1, 0]
for exp_type in plot_df['experiment_type'].unique():
    subset = plot_df[plot_df['experiment_type'] == exp_type]
    mean_by_coef = subset.groupby('coefficient')['formality_score'].mean()
    ax3.plot(mean_by_coef.index, mean_by_coef.values, marker='o', label=exp_type, linewidth=2)
ax3.axhline(y=0.5, color='r', linestyle='--', alpha=0.5)
ax3.axvline(x=0, color='gray', linestyle=':', alpha=0.5)
ax3.set_xlabel('Steering Coefficient')
ax3.set_ylabel('Mean Formality Score')
ax3.set_title('Formality by Experiment Type')
ax3.legend()
ax3.grid(True, alpha=0.3)

# 4. By sentence language
ax4 = axes[1, 1]
for sent_lang in ['english', 'hebrew', 'russian', 'german']:
    subset = plot_df[plot_df['sentence_language'] == sent_lang]
    mean_by_coef = subset.groupby('coefficient')['formality_score'].mean()
    ax4.plot(mean_by_coef.index, mean_by_coef.values, marker='o', label=sent_lang.capitalize(), linewidth=2)
ax4.axhline(y=0.5, color='r', linestyle='--', alpha=0.5)
ax4.axvline(x=0, color='gray', linestyle=':', alpha=0.5)
ax4.set_xlabel('Steering Coefficient')
ax4.set_ylabel('Mean Formality Score')
ax4.set_title('Formality by Sentence Language')
ax4.legend()
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('cross_linguistic_steering_overview.png', dpi=150, bbox_inches='tight')
plt.show()

# Figure 2: Cross-linguistic transfer matrix
fig, axes = plt.subplots(1, 4, figsize=(22, 5))  # Changed to 4 subplots

# For each sentence language, show effect of different feature sources
for idx, sent_lang in enumerate(['english', 'hebrew', 'russian', 'german']):
    ax = axes[idx]

    feat_sources = ['universal']
    if sent_lang != 'german':
        feat_sources = ['english', 'hebrew', 'russian', 'universal']

    for feat_src in feat_sources:
        subset = valid_df[(valid_df['sentence_language'] == sent_lang) &
                          (valid_df['feature_source'] == feat_src)]
        if len(subset) > 0:
            mean_by_coef = subset.groupby('coefficient')['formality_score'].mean()
            style = '-' if feat_src == sent_lang else ('--' if feat_src == 'universal' else ':')
            marker = 'o' if feat_src == sent_lang else ('s' if feat_src == 'universal' else '^')
            ax.plot(mean_by_coef.index, mean_by_coef.values,
                   linestyle=style, marker=marker, label=f'{feat_src} features', linewidth=2)

    ax.axhline(y=0.5, color='r', linestyle='--', alpha=0.3)
    ax.axvline(x=0, color='gray', linestyle=':', alpha=0.3)
    ax.set_xlabel('Steering Coefficient')
    ax.set_ylabel('Mean Formality Score')
    ax.set_title(f'{sent_lang.upper()} Sentences')
    ax.legend(loc='best', fontsize=8)
    ax.grid(True, alpha=0.3)

plt.suptitle('Cross-Linguistic Steering Transfer', fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig('cross_linguistic_transfer_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

# Figure 3: Heatmap of effect sizes
# Create pivot table for effect sizes (formal - slang)
effect_matrix = summary_df.pivot(index='sentence_language', columns='feature_source', values='effect_size')

fig, ax = plt.subplots(figsize=(10, 6))
sns.heatmap(effect_matrix, annot=True, fmt='.3f', cmap='RdYlBu', center=0,
            cbar_kws={'label': 'Effect Size (Formal - Slang)'}, ax=ax)
ax.set_xlabel('Feature Source')
ax.set_ylabel('Sentence Language')
ax.set_title('Cross-Linguistic Steering Effect Sizes\n(Positive = Steering Works, Formal > Slang)')
plt.tight_layout()
plt.savefig('cross_linguistic_effect_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# Figure 4: Violin plots by steering direction
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for idx, exp_type in enumerate(['same_language', 'cross_language', 'universal']):
    ax = axes[idx]
    subset = valid_df[valid_df['experiment_type'] == exp_type]

    if len(subset) > 0:
        # Create groups
        formal = subset[subset['coefficient'] < 0]['formality_score'].values
        baseline = subset[subset['coefficient'] == 0]['formality_score'].values
        slang = subset[subset['coefficient'] > 0]['formality_score'].values

        data = [formal, baseline, slang]
        labels = ['Formal\n(coef<0)', 'Baseline\n(coef=0)', 'Slang\n(coef>0)']

        parts = ax.violinplot(data, positions=[0, 1, 2], showmeans=True, showmedians=True)
        ax.set_xticks([0, 1, 2])
        ax.set_xticklabels(labels)
        ax.axhline(y=0.5, color='r', linestyle='--', alpha=0.5)
        ax.set_ylabel('Formality Score')
        ax.set_title(f'{exp_type.replace("_", " ").title()}')
        ax.set_ylim(0, 1)

plt.suptitle('Formality Distribution by Steering Direction', fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig('steering_direction_violins.png', dpi=150, bbox_inches='tight')
plt.show()

# Figure 6: Universal & Exclusive Features Steering - Heatmaps Per Language
print("="*80)
print("UNIVERSAL & EXCLUSIVE FEATURES STEERING BY LANGUAGE")
print("="*80)

!pip install python-bidi -q

from bidi.algorithm import get_display
import numpy as np

def fix_hebrew_text(text):
    """Fix Hebrew text for proper RTL display in matplotlib."""
    try:
        return get_display(text)
    except:
        return text

# Define which feature sources to plot for each language
language_experiments = {
    'english': ['universal', 'heb_rus_excl'],
    'hebrew': ['universal', 'eng_rus_excl'],
    'russian': ['universal', 'heb_eng_excl'],
    'german': ['universal'],
}

for sent_lang, feat_sources in language_experiments.items():
    for feat_src in feat_sources:
        fig, ax = plt.subplots(figsize=(14, 10))

        # Use results_df to get ALL data including NaN scores
        subset = valid_df[(valid_df['feature_source'] == feat_src) &
                          (valid_df['sentence_language'] == sent_lang) ]

        if len(subset) > 0:
            pivot = subset.pivot_table(values='formality_score', index='prompt',
                                       columns='coefficient', aggfunc='mean')

            if len(pivot) > 0:
                # Count missing values
                n_missing = pivot.isna().sum().sum()
                print(f"{sent_lang.upper()} + {feat_src.upper()}: {n_missing} missing scores")

                # For Hebrew, fix the index labels
                if sent_lang == 'hebrew':
                    pivot.index = [fix_hebrew_text(str(idx)) for idx in pivot.index]

                # Create mask for NaN values
                mask = pivot.isna()

                # Plot heatmap - NaN cells will be white/blank due to mask
                sns.heatmap(pivot, cmap='RdYlBu_r', center=0.5, annot=True, fmt='.2f', ax=ax,
                            cbar_kws={'label': 'Formality Score (0=Informal, 1=Formal)'},
                            annot_kws={'size': 8},
                            linewidths=0.5,
                            linecolor='lightgray')

                # Manually add "N/A" text for NaN cells
                for i in range(len(pivot.index)):
                    for j in range(len(pivot.columns)):
                        if pd.isna(pivot.iloc[i, j]):
                            ax.text(j + 0.5, i + 0.5, 'N/A', ha='center', va='center',
                                   fontsize=8, color='black', fontweight='bold')

                ax.set_xlabel('Steering Coefficient', fontsize=12)
                ax.set_ylabel('Prompt', fontsize=12)

                # Create descriptive title
                if feat_src == 'universal':
                    title_feat = 'Universal Features'
                elif feat_src == 'heb_rus_excl':
                    title_feat = 'Hebrew+Russian (excl. English) Features'
                elif feat_src == 'eng_rus_excl':
                    title_feat = 'English+Russian (excl. Hebrew) Features'
                elif feat_src == 'heb_eng_excl':
                    title_feat = 'Hebrew+English (excl. Russian) Features'
                else:
                    title_feat = f'{feat_src} Features'

                ax.set_title(f'{title_feat} → {sent_lang.upper()} Sentences\n(Blue=Informal/Slang, Red=Formal)',
                            fontsize=14)

                plt.yticks(fontsize=9)
                plt.xticks(rotation=0)

        plt.tight_layout()
        plt.savefig(f'{feat_src}_steering_{sent_lang}.png', dpi=150, bbox_inches='tight')
        plt.show()
        print("\n")

# Figure 6: Universal & Exclusive Features Steering - Heatmaps Per Language
print("="*80)
print("UNIVERSAL & EXCLUSIVE FEATURES STEERING BY LANGUAGE")
print("="*80)

!pip install python-bidi -q

from bidi.algorithm import get_display
import numpy as np

def fix_hebrew_text(text):
    """Fix Hebrew text for proper RTL display in matplotlib."""
    try:
        return get_display(text)
    except:
        return text

# Define which feature sources to plot for each language
language_experiments = {
    'english': ['universal', 'heb_rus_excl'],
    'hebrew': ['universal', 'eng_rus_excl'],
    'russian': ['universal', 'heb_eng_excl'],
    'german': ['universal'],
}

for sent_lang, feat_sources in language_experiments.items():
    for feat_src in feat_sources:
        fig, ax = plt.subplots(figsize=(14, 10))

        # Use results_df to get ALL data including NaN scores
        subset = valid_df[(valid_df['feature_source'] == feat_src) &
                          (valid_df['sentence_language'] == sent_lang) &
                          (valid_df['coefficient'] >= -200) &
                          (valid_df['coefficient'] <= 200)].copy()

        if len(subset) > 0:
            pivot = subset.pivot_table(values='formality_score', index='prompt',
                                       columns='coefficient', aggfunc='mean')

            if len(pivot) > 0:
                # Count missing values
                n_missing = pivot.isna().sum().sum()
                print(f"{sent_lang.upper()} + {feat_src.upper()}: {n_missing} missing scores")

                # For Hebrew, fix the index labels
                if sent_lang == 'hebrew':
                    pivot.index = [fix_hebrew_text(str(idx)) for idx in pivot.index]

                # Create mask for NaN values
                mask = pivot.isna()

                # Plot heatmap - NaN cells will be white/blank due to mask
                sns.heatmap(pivot, cmap='RdYlBu_r', center=0.5, annot=True, fmt='.2f', ax=ax,
                            cbar_kws={'label': 'Formality Score (0=Informal, 1=Formal)'},
                            annot_kws={'size': 8},
                            linewidths=0.5,
                            linecolor='lightgray')

                # Manually add "N/A" text for NaN cells
                for i in range(len(pivot.index)):
                    for j in range(len(pivot.columns)):
                        if pd.isna(pivot.iloc[i, j]):
                            ax.text(j + 0.5, i + 0.5, 'N/A', ha='center', va='center',
                                   fontsize=8, color='black', fontweight='bold')

                ax.set_xlabel('Steering Coefficient', fontsize=12)
                ax.set_ylabel('Prompt', fontsize=12)

                # Create descriptive title
                if feat_src == 'universal':
                    title_feat = 'Universal Features'
                elif feat_src == 'heb_rus_excl':
                    title_feat = 'Hebrew+Russian (excl. English) Features'
                elif feat_src == 'eng_rus_excl':
                    title_feat = 'English+Russian (excl. Hebrew) Features'
                elif feat_src == 'heb_eng_excl':
                    title_feat = 'Hebrew+English (excl. Russian) Features'
                else:
                    title_feat = f'{feat_src} Features'

                ax.set_title(f'{title_feat} → {sent_lang.upper()} Sentences\n(Blue=Informal/Slang, Red=Formal)',
                            fontsize=14)

                plt.yticks(fontsize=9)
                plt.xticks(rotation=0)

        plt.tight_layout()
        plt.savefig(f'{feat_src}_steering_{sent_lang}.png', dpi=150, bbox_inches='tight')
        plt.show()
        print("\n")

# Heatmap: Universal features effect across all 4 languages
print("="*80)
print("UNIVERSAL FEATURES - HEATMAP ACROSS ALL LANGUAGES")
print("="*80)

# Get universal features data for all languages, filtered to coefficient range
universal_df = valid_df[(valid_df['feature_source'] == 'universal') &
                        (valid_df['coefficient'] >= -200) &
                        (valid_df['coefficient'] <= 200)].copy()

# Create pivot table: rows = language, columns = coefficient, values = mean formality
pivot = universal_df.pivot_table(values='formality_score',
                                  index='sentence_language',
                                  columns='coefficient',
                                  aggfunc='mean')

# Reorder rows
row_order = ['english', 'hebrew', 'russian', 'german']
pivot = pivot.reindex([lang for lang in row_order if lang in pivot.index])

# Capitalize row labels
pivot.index = [lang.capitalize() for lang in pivot.index]

fig, ax = plt.subplots(figsize=(12, 5))

sns.heatmap(pivot, cmap='RdYlBu_r', center=0.5, annot=True, fmt='.2f', ax=ax,
            cbar_kws={'label': 'Formality Score (0=Informal, 1=Formal)'},
            annot_kws={'size': 10},
            linewidths=0.5,
            linecolor='lightgray')

ax.set_xlabel('Steering Coefficient', fontsize=12)
ax.set_ylabel('Language', fontsize=12)
ax.set_title('Universal Features Steering Effect Across Languages\n(Blue=Informal/Slang, Red=Formal)', fontsize=14)

plt.tight_layout()
plt.savefig('universal_heatmap_all_languages.png', dpi=150, bbox_inches='tight')
plt.show()

print("\nMean formality by language and coefficient:")
print(pivot.to_string())

# Mean formality across all languages for Universal features
print("="*80)
print("UNIVERSAL FEATURES - MEAN ACROSS ALL LANGUAGES")
print("="*80)

# Get universal features data for all languages, filtered to coefficient range
universal_df = valid_df[(valid_df['feature_source'] == 'universal') &
                        (valid_df['coefficient'] >= -200) &
                        (valid_df['coefficient'] <= 200)].copy()

# Calculate mean formality by coefficient across all languages
mean_by_coef = universal_df.groupby('coefficient')['formality_score'].agg(['mean', 'std', 'count'])

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: Line plot with error bars
ax1 = axes[0]
ax1.errorbar(mean_by_coef.index, mean_by_coef['mean'], yerr=mean_by_coef['std'],
             marker='o', capsize=5, linewidth=2, markersize=8, color='blue')
ax1.axhline(y=0.5, color='r', linestyle='--', alpha=0.5, label='Neutral (0.5)')
ax1.axvline(x=0, color='gray', linestyle=':', alpha=0.5)
ax1.set_xlabel('Steering Coefficient', fontsize=12)
ax1.set_ylabel('Mean Formality Score', fontsize=12)
ax1.set_title('Universal Features: Mean Formality Across All Languages\n(with std error bars)', fontsize=12)
ax1.grid(True, alpha=0.3)
ax1.legend()

# Plot 2: Bar plot
ax2 = axes[1]
colors = ['#d73027' if x < 0 else '#4575b4' if x > 0 else 'gray' for x in mean_by_coef.index]
ax2.bar(range(len(mean_by_coef)), mean_by_coef['mean'], color=colors, edgecolor='black')
ax2.set_xticks(range(len(mean_by_coef)))
ax2.set_xticklabels(mean_by_coef.index, rotation=45)
ax2.axhline(y=0.5, color='r', linestyle='--', alpha=0.5)
ax2.set_xlabel('Steering Coefficient', fontsize=12)
ax2.set_ylabel('Mean Formality Score', fontsize=12)
ax2.set_title('Universal Features: Mean Formality by Coefficient\n(Red=Formal direction, Blue=Slang direction)', fontsize=12)

plt.tight_layout()
plt.savefig('universal_mean_all_languages.png', dpi=150, bbox_inches='tight')
plt.show()

# Print summary table
print("\nSummary Table:")
print(mean_by_coef.to_string())

# Also show per-language comparison
print("\n" + "="*80)
print("BREAKDOWN BY LANGUAGE (Universal features only)")
print("="*80)
for lang in ['english', 'hebrew', 'russian', 'german']:
    lang_subset = universal_df[universal_df['sentence_language'] == lang]
    if len(lang_subset) > 0:
        lang_mean = lang_subset.groupby('coefficient')['formality_score'].mean()
        print(f"\n{lang.upper()}:")
        print(lang_mean.to_string())

"""## 13. Final Summary"""

print("="*80)
print("FINAL SUMMARY: CROSS-LINGUISTIC STEERING EXPERIMENT")
print("="*80)

print("\n" + "="*80)
print("1. EXPERIMENTAL SETUP")
print("="*80)
print(f"   • Steering Layer: {STEERING_LAYER}")
print(f"   • Coefficients: {COEFFICIENTS}")
print(f"   • Total experiments: {len(EXPERIMENTS)}")
print(f"   • Total generations: {len(valid_df)}")

print("\n" + "="*80)
print("2. FEATURE SETS USED")
print("="*80)
for name, features in FEATURE_SETS.items():
    print(f"   • {name.upper():12s}: {len(features)} features")

print("\n" + "="*80)
print("3. OVERALL RESULTS")
print("="*80)
print(f"   • Overall Pearson r: {correlation:.4f} (p={p_value:.2e})")
print(f"   • Overall Spearman ρ: {spearman_corr:.4f} (p={spearman_p:.2e})")
if correlation < 0:
    print(f"   • Interpretation: STEERING WORKS - Higher coef → Lower formality (more slang)")

print("\n" + "="*80)
print("4. BY EXPERIMENT TYPE")
print("="*80)
for _, row in exp_stats_df.iterrows():
    status = "✓" if row['correlation'] < 0 and row['p_value'] < 0.05 else "✗"
    print(f"   {status} {row['experiment_type']:15s}: r={row['correlation']:+.4f} (p={row['p_value']:.2e})")

print("\n" + "="*80)
print("5. CROSS-LINGUISTIC TRANSFER EFFECTIVENESS")
print("="*80)
print("   Effect Size = Mean(Formal) - Mean(Slang)")
print("   Positive effect = steering works as expected\n")
print(effect_matrix.to_string())

print("\n" + "="*80)
print("6. KEY FINDINGS")
print("="*80)

# Find best and worst transfers
if len(summary_df) > 0:
    best = summary_df.loc[summary_df['effect_size'].idxmax()]
    worst = summary_df.loc[summary_df['effect_size'].idxmin()]

    print(f"   • Best transfer: {best['feature_source']}→{best['sentence_language']} (effect={best['effect_size']:.4f})")
    print(f"   • Worst transfer: {worst['feature_source']}→{worst['sentence_language']} (effect={worst['effect_size']:.4f})")

    # Universal features effectiveness
    universal_effects = summary_df[summary_df['feature_source'] == 'universal']['effect_size']
    print(f"   • Universal features avg effect: {universal_effects.mean():.4f}")

    # Same-language effectiveness
    same_lang = summary_df[summary_df['transfer_type'] == 'SAME']['effect_size']
    cross_lang = summary_df[summary_df['transfer_type'] == 'CROSS']['effect_size']
    print(f"   • Same-language avg effect: {same_lang.mean():.4f}")
    print(f"   • Cross-language avg effect: {cross_lang.mean():.4f}")

print("\n" + "="*80)
print("✓ EXPERIMENT COMPLETE")
print("="*80)

# Save results
valid_df.to_csv('cross_linguistic_steering_results.csv', index=False)
summary_df.to_csv('cross_linguistic_summary.csv', index=False)
specific_df.to_csv('experiment_correlations.csv', index=False)

print("\n✓ Results saved to:")
print("  • cross_linguistic_steering_results.csv")
print("  • cross_linguistic_summary.csv")
print("  • experiment_correlations.csv")

# Save all generated results to CSV
print("="*80)
print("SAVING ALL RESULTS")
print("="*80)

# 1. Save complete results (all generations with scores)
results_df.to_csv('all_generated_results.csv', index=False)
print(f"✓ Saved all_generated_results.csv ({len(results_df)} rows)")

# 2. Save only the formality scores (for quick reload)
scores_df = valid_df[['sentence_language', 'feature_source', 'prompt', 'coefficient',
                        'generated_text', 'formality_score', 'steering_direction']].copy()
scores_df.to_csv('formality_scores.csv', index=False)
print(f"✓ Saved formality_scores.csv ({len(scores_df)} rows)")

# 3. Save valid_df (filtered results)
valid_df.to_csv('valid_results_filtered.csv', index=False)
print(f"✓ Saved valid_results_filtered.csv ({len(valid_df)} rows)")

# Show file sizes
import os
for fname in ['all_generated_results.csv', 'formality_scores.csv', 'valid_results_filtered.csv']:
    size = os.path.getsize(fname) / 1024
    print(f"   {fname}: {size:.1f} KB")

print("\n✓ All files saved!")

"""## 14. Bonus: Example Outputs Comparison"""

print("="*80)
print("EXAMPLE OUTPUTS: EXTREME COEFFICIENTS")
print("="*80)

# Show examples at extreme coefficients
extreme_coefs = [-200, 0, 700]
sample_prompts = [
    "I think that",
    "אני חושב ש",
    "Я думаю, что",
]

for prompt in sample_prompts:
    print(f"\n{'='*60}")
    print(f"PROMPT: {prompt}")
    print(f"{'='*60}")

    for coef in extreme_coefs:
        subset = valid_df[(valid_df['prompt'] == prompt) & (valid_df['coefficient'] == coef)]
        if len(subset) > 0:
            row = subset.iloc[0]
            direction = "FORMAL" if coef < 0 else ("BASELINE" if coef == 0 else "SLANG")
            print(f"\n[{coef:+4d}] {direction} (formality={row['formality_score']:.3f}):")
            print(f"  {row['generated_text'][:150]}...")

from google.colab import files
import os

# List all files in /content
print("Files in /content:")
for f in os.listdir('/content'):
    if os.path.isfile(f'/content/{f}'):
        print(f"  {f}")

# Download all files (uncomment the ones you want)
for f in os.listdir('/content'):
    if f.endswith(('.csv', '.png')):  # Download CSVs and PNGs
        files.download(f'/content/{f}')
        print(f"Downloaded: {f}")